package neu.edu.entity;
// Generated Dec 12, 2017 2:06:43 PM by Hibernate Tools 5.2.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * CategoryStartup generated by hbm2java
 */
@Entity
@Table(name = "category_startup", catalog = "webdevelopment")
public class CategoryStartup implements java.io.Serializable {

	private Integer categoryStartupId;
	private Category category;
	private Person person;

	public CategoryStartup() {
	}

	public CategoryStartup(Category category, Person person) {
		this.category = category;
		this.person = person;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "category_startup_id", unique = true, nullable = false)
	public Integer getCategoryStartupId() {
		return this.categoryStartupId;
	}

	public void setCategoryStartupId(Integer categoryStartupId) {
		this.categoryStartupId = categoryStartupId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "category_id", nullable = false)
	public Category getCategory() {
		return this.category;
	}

	public void setCategory(Category category) {
		this.category = category;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "person_id", nullable = false)
	public Person getPerson() {
		return this.person;
	}

	public void setPerson(Person person) {
		this.person = person;
	}

}
