package neu.edu.entity;
// Generated Dec 10, 2017 6:49:41 PM by Hibernate Tools 5.2.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * CategoryStartup generated by hbm2java
 */
@Entity
@Table(name = "category_startup", catalog = "webdevelopment")
public class CategoryStartup implements java.io.Serializable {

	private Integer idcategoryStartup;
	private Category category;
	private Person person;

	public CategoryStartup() {
	}

	public CategoryStartup(Category category, Person person) {
		this.category = category;
		this.person = person;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idcategory_startup", unique = true, nullable = false)
	public Integer getIdcategoryStartup() {
		return this.idcategoryStartup;
	}

	public void setIdcategoryStartup(Integer idcategoryStartup) {
		this.idcategoryStartup = idcategoryStartup;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idcategory", nullable = false)
	public Category getCategory() {
		return this.category;
	}

	public void setCategory(Category category) {
		this.category = category;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idperson", nullable = false)
	public Person getPerson() {
		return this.person;
	}

	public void setPerson(Person person) {
		this.person = person;
	}

}
