package neu.edu.entity;
// Generated Dec 10, 2017 6:49:41 PM by Hibernate Tools 5.2.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Funding generated by hbm2java
 */
@Entity
@Table(name = "funding", catalog = "webdevelopment")
public class Funding implements java.io.Serializable {

	private Integer idfunding;
	private Idea idea;
	private User user;
	private Integer fundingValue;
	private Byte fundedRecieved;

	public Funding() {
	}

	public Funding(Idea idea, User user) {
		this.idea = idea;
		this.user = user;
	}

	public Funding(Idea idea, User user, Integer fundingValue, Byte fundedRecieved) {
		this.idea = idea;
		this.user = user;
		this.fundingValue = fundingValue;
		this.fundedRecieved = fundedRecieved;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idfunding", unique = true, nullable = false)
	public Integer getIdfunding() {
		return this.idfunding;
	}

	public void setIdfunding(Integer idfunding) {
		this.idfunding = idfunding;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ididea", nullable = false)
	public Idea getIdea() {
		return this.idea;
	}

	public void setIdea(Idea idea) {
		this.idea = idea;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "iduser", nullable = false)
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@Column(name = "fundingValue")
	public Integer getFundingValue() {
		return this.fundingValue;
	}

	public void setFundingValue(Integer fundingValue) {
		this.fundingValue = fundingValue;
	}

	@Column(name = "fundedRecieved")
	public Byte getFundedRecieved() {
		return this.fundedRecieved;
	}

	public void setFundedRecieved(Byte fundedRecieved) {
		this.fundedRecieved = fundedRecieved;
	}

}
