package neu.edu.entity;
// Generated Dec 12, 2017 2:06:43 PM by Hibernate Tools 5.2.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Funding generated by hbm2java
 */
@Entity
@Table(name = "funding", catalog = "webdevelopment")
public class Funding implements java.io.Serializable {

	private Integer fundingId;
	private Idea idea;
	private User user;
	private Integer fundingValue;
	private Byte fundedRecieved;

	public Funding() {
	}

	public Funding(Idea idea, User user) {
		this.idea = idea;
		this.user = user;
	}

	public Funding(Idea idea, User user, Integer fundingValue, Byte fundedRecieved) {
		this.idea = idea;
		this.user = user;
		this.fundingValue = fundingValue;
		this.fundedRecieved = fundedRecieved;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "funding_id", unique = true, nullable = false)
	public Integer getFundingId() {
		return this.fundingId;
	}

	public void setFundingId(Integer fundingId) {
		this.fundingId = fundingId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idea_id", nullable = false)
	public Idea getIdea() {
		return this.idea;
	}

	public void setIdea(Idea idea) {
		this.idea = idea;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "user_id", nullable = false)
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@Column(name = "funding_value")
	public Integer getFundingValue() {
		return this.fundingValue;
	}

	public void setFundingValue(Integer fundingValue) {
		this.fundingValue = fundingValue;
	}

	@Column(name = "funded_recieved")
	public Byte getFundedRecieved() {
		return this.fundedRecieved;
	}

	public void setFundedRecieved(Byte fundedRecieved) {
		this.fundedRecieved = fundedRecieved;
	}

}
