package neu.edu.entity;
// Generated Dec 12, 2017 2:06:43 PM by Hibernate Tools 5.2.5.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Idea generated by hbm2java
 */
@Entity
@Table(name = "idea", catalog = "webdevelopment")
public class Idea implements java.io.Serializable {

	private Integer ideaId;
	private Bid bid;
	private Category category;
	private String ideaName;
	private String ideaDesc;
	private String goalFunding;
	private String duration;
	private String status;
	private String reason;
	private Integer compilationPercentage;
	private Date startDate;
	private String createdBy;
	private Date createdOn;
	private String endDate;
	private Set<Funding> fundings = new HashSet<Funding>(0);
	private Set<IdeaService> ideaServices = new HashSet<IdeaService>(0);

	public Idea() {
	}

	public Idea(Category category, String ideaName, String ideaDesc, String goalFunding, String duration,
			Date startDate, String createdBy) {
		this.category = category;
		this.ideaName = ideaName;
		this.ideaDesc = ideaDesc;
		this.goalFunding = goalFunding;
		this.duration = duration;
		this.startDate = startDate;
		this.createdBy = createdBy;
	}

	public Idea(Bid bid, Category category, String ideaName, String ideaDesc, String goalFunding, String duration,
			String status, String reason, Integer compilationPercentage, Date startDate, String createdBy,
			Date createdOn, String endDate, Set<Funding> fundings, Set<IdeaService> ideaServices) {
		this.bid = bid;
		this.category = category;
		this.ideaName = ideaName;
		this.ideaDesc = ideaDesc;
		this.goalFunding = goalFunding;
		this.duration = duration;
		this.status = status;
		this.reason = reason;
		this.compilationPercentage = compilationPercentage;
		this.startDate = startDate;
		this.createdBy = createdBy;
		this.createdOn = createdOn;
		this.endDate = endDate;
		this.fundings = fundings;
		this.ideaServices = ideaServices;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idea_id", unique = true, nullable = false)
	public Integer getIdeaId() {
		return this.ideaId;
	}

	public void setIdeaId(Integer ideaId) {
		this.ideaId = ideaId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "bid_id")
	public Bid getBid() {
		return this.bid;
	}

	public void setBid(Bid bid) {
		this.bid = bid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "category_id", nullable = false)
	public Category getCategory() {
		return this.category;
	}

	public void setCategory(Category category) {
		this.category = category;
	}

	@Column(name = "idea_name", nullable = false, length = 45)
	public String getIdeaName() {
		return this.ideaName;
	}

	public void setIdeaName(String ideaName) {
		this.ideaName = ideaName;
	}

	@Column(name = "idea_desc", nullable = false, length = 45)
	public String getIdeaDesc() {
		return this.ideaDesc;
	}

	public void setIdeaDesc(String ideaDesc) {
		this.ideaDesc = ideaDesc;
	}

	@Column(name = "goal_funding", nullable = false, length = 45)
	public String getGoalFunding() {
		return this.goalFunding;
	}

	public void setGoalFunding(String goalFunding) {
		this.goalFunding = goalFunding;
	}

	@Column(name = "duration", nullable = false, length = 45)
	public String getDuration() {
		return this.duration;
	}

	public void setDuration(String duration) {
		this.duration = duration;
	}

	@Column(name = "status", length = 45)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Column(name = "reason", length = 45)
	public String getReason() {
		return this.reason;
	}

	public void setReason(String reason) {
		this.reason = reason;
	}

	@Column(name = "compilation_percentage")
	public Integer getCompilationPercentage() {
		return this.compilationPercentage;
	}

	public void setCompilationPercentage(Integer compilationPercentage) {
		this.compilationPercentage = compilationPercentage;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "start_date", nullable = false, length = 19)
	public Date getStartDate() {
		return this.startDate;
	}

	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}

	@Column(name = "created_by", nullable = false, length = 45)
	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_on", length = 19)
	public Date getCreatedOn() {
		return this.createdOn;
	}

	public void setCreatedOn(Date createdOn) {
		this.createdOn = createdOn;
	}

	@Column(name = "end_date", length = 45)
	public String getEndDate() {
		return this.endDate;
	}

	public void setEndDate(String endDate) {
		this.endDate = endDate;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "idea")
	public Set<Funding> getFundings() {
		return this.fundings;
	}

	public void setFundings(Set<Funding> fundings) {
		this.fundings = fundings;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "idea")
	public Set<IdeaService> getIdeaServices() {
		return this.ideaServices;
	}

	public void setIdeaServices(Set<IdeaService> ideaServices) {
		this.ideaServices = ideaServices;
	}

}
