package neu.edu.entity;
// Generated Dec 10, 2017 6:49:41 PM by Hibernate Tools 5.2.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * IdeaService generated by hbm2java
 */
@Entity
@Table(name = "idea_service", catalog = "webdevelopment")
public class IdeaService implements java.io.Serializable {

	private Integer idideaService;
	private Idea idea;
	private Services services;
	private Set<Bid> bids = new HashSet<Bid>(0);

	public IdeaService() {
	}

	public IdeaService(Idea idea, Services services) {
		this.idea = idea;
		this.services = services;
	}

	public IdeaService(Idea idea, Services services, Set<Bid> bids) {
		this.idea = idea;
		this.services = services;
		this.bids = bids;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ididea_service", unique = true, nullable = false)
	public Integer getIdideaService() {
		return this.idideaService;
	}

	public void setIdideaService(Integer idideaService) {
		this.idideaService = idideaService;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ididea", nullable = false)
	public Idea getIdea() {
		return this.idea;
	}

	public void setIdea(Idea idea) {
		this.idea = idea;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idservices", nullable = false)
	public Services getServices() {
		return this.services;
	}

	public void setServices(Services services) {
		this.services = services;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ideaService")
	public Set<Bid> getBids() {
		return this.bids;
	}

	public void setBids(Set<Bid> bids) {
		this.bids = bids;
	}

}
