package neu.edu.entity;
// Generated Dec 10, 2017 6:49:41 PM by Hibernate Tools 5.2.5.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Services generated by hbm2java
 */
@Entity
@Table(name = "services", catalog = "webdevelopment")
public class Services implements java.io.Serializable {

	private Integer idservices;
	private String servicesName;
	private String servicesDesc;
	private Date createdOn;
	private Date createdBy;
	private Set<IdeaService> ideaServices = new HashSet<IdeaService>(0);

	public Services() {
	}

	public Services(String servicesName, String servicesDesc) {
		this.servicesName = servicesName;
		this.servicesDesc = servicesDesc;
	}

	public Services(String servicesName, String servicesDesc, Date createdOn, Date createdBy,
			Set<IdeaService> ideaServices) {
		this.servicesName = servicesName;
		this.servicesDesc = servicesDesc;
		this.createdOn = createdOn;
		this.createdBy = createdBy;
		this.ideaServices = ideaServices;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idservices", unique = true, nullable = false)
	public Integer getIdservices() {
		return this.idservices;
	}

	public void setIdservices(Integer idservices) {
		this.idservices = idservices;
	}

	@Column(name = "servicesName", nullable = false, length = 45)
	public String getServicesName() {
		return this.servicesName;
	}

	public void setServicesName(String servicesName) {
		this.servicesName = servicesName;
	}

	@Column(name = "servicesDesc", nullable = false, length = 45)
	public String getServicesDesc() {
		return this.servicesDesc;
	}

	public void setServicesDesc(String servicesDesc) {
		this.servicesDesc = servicesDesc;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "createdOn", length = 19)
	public Date getCreatedOn() {
		return this.createdOn;
	}

	public void setCreatedOn(Date createdOn) {
		this.createdOn = createdOn;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "createdBy", length = 19)
	public Date getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(Date createdBy) {
		this.createdBy = createdBy;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "services")
	public Set<IdeaService> getIdeaServices() {
		return this.ideaServices;
	}

	public void setIdeaServices(Set<IdeaService> ideaServices) {
		this.ideaServices = ideaServices;
	}

}
